---
- name: Create nginx config file from template
  template:
    src: site.conf.j2
    dest: "/etc/nginx/sites-available/{{ domain_name }}.conf"
    owner: root
    group: root
    mode: '0644'

- name: Enable site by creating symlink
  file:
    src: "/etc/nginx/sites-available/{{ domain_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ domain_name }}.conf"
    state: link

- name: Test nginx config
  command: nginx -t
  register: nginx_test
  changed_when: nginx_test.rc != 0
  failed_when: nginx_test.rc != 0


- name: Reload nginx
  service:
    name: nginx
    state: reloaded


# - name: Generate SSL certificate with certbot
#   command: >
#     certbot --nginx -n --agree-tos
#     -m {{ certbot_email }}
#     -d {{ domain_name }}
#   notify: Reload nginx
#   when: certbot_email is defined
